//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CinemaClient.CinemaServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ShowtimeDto", Namespace="http://schemas.datacontract.org/2004/07/DataEntity")]
    [System.SerializableAttribute()]
    public partial class ShowtimeDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> HallIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HallNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> MovieIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MovieTitleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime ShowtimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ShowtimeIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal TicketPriceField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> HallID {
            get {
                return this.HallIDField;
            }
            set {
                if ((this.HallIDField.Equals(value) != true)) {
                    this.HallIDField = value;
                    this.RaisePropertyChanged("HallID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string HallName {
            get {
                return this.HallNameField;
            }
            set {
                if ((object.ReferenceEquals(this.HallNameField, value) != true)) {
                    this.HallNameField = value;
                    this.RaisePropertyChanged("HallName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> MovieID {
            get {
                return this.MovieIDField;
            }
            set {
                if ((this.MovieIDField.Equals(value) != true)) {
                    this.MovieIDField = value;
                    this.RaisePropertyChanged("MovieID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MovieTitle {
            get {
                return this.MovieTitleField;
            }
            set {
                if ((object.ReferenceEquals(this.MovieTitleField, value) != true)) {
                    this.MovieTitleField = value;
                    this.RaisePropertyChanged("MovieTitle");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Showtime {
            get {
                return this.ShowtimeField;
            }
            set {
                if ((this.ShowtimeField.Equals(value) != true)) {
                    this.ShowtimeField = value;
                    this.RaisePropertyChanged("Showtime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ShowtimeID {
            get {
                return this.ShowtimeIDField;
            }
            set {
                if ((this.ShowtimeIDField.Equals(value) != true)) {
                    this.ShowtimeIDField = value;
                    this.RaisePropertyChanged("ShowtimeID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal TicketPrice {
            get {
                return this.TicketPriceField;
            }
            set {
                if ((this.TicketPriceField.Equals(value) != true)) {
                    this.TicketPriceField = value;
                    this.RaisePropertyChanged("TicketPrice");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MovieDto", Namespace="http://schemas.datacontract.org/2004/07/DataEntity")]
    [System.SerializableAttribute()]
    public partial class MovieDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int MovieIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TitleField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MovieID {
            get {
                return this.MovieIDField;
            }
            set {
                if ((this.MovieIDField.Equals(value) != true)) {
                    this.MovieIDField = value;
                    this.RaisePropertyChanged("MovieID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Title {
            get {
                return this.TitleField;
            }
            set {
                if ((object.ReferenceEquals(this.TitleField, value) != true)) {
                    this.TitleField = value;
                    this.RaisePropertyChanged("Title");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="HallDto", Namespace="http://schemas.datacontract.org/2004/07/DataEntity")]
    [System.SerializableAttribute()]
    public partial class HallDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int HallIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HallNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int HallID {
            get {
                return this.HallIDField;
            }
            set {
                if ((this.HallIDField.Equals(value) != true)) {
                    this.HallIDField = value;
                    this.RaisePropertyChanged("HallID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string HallName {
            get {
                return this.HallNameField;
            }
            set {
                if ((object.ReferenceEquals(this.HallNameField, value) != true)) {
                    this.HallNameField = value;
                    this.RaisePropertyChanged("HallName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CinemaServiceReference.ICinemaService")]
    public interface ICinemaService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICinemaService/GetAllShowtimes", ReplyAction="http://tempuri.org/ICinemaService/GetAllShowtimesResponse")]
        CinemaClient.CinemaServiceReference.ShowtimeDto[] GetAllShowtimes();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICinemaService/GetAllShowtimes", ReplyAction="http://tempuri.org/ICinemaService/GetAllShowtimesResponse")]
        System.Threading.Tasks.Task<CinemaClient.CinemaServiceReference.ShowtimeDto[]> GetAllShowtimesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICinemaService/GetShowtimeById", ReplyAction="http://tempuri.org/ICinemaService/GetShowtimeByIdResponse")]
        CinemaClient.CinemaServiceReference.ShowtimeDto GetShowtimeById(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICinemaService/GetShowtimeById", ReplyAction="http://tempuri.org/ICinemaService/GetShowtimeByIdResponse")]
        System.Threading.Tasks.Task<CinemaClient.CinemaServiceReference.ShowtimeDto> GetShowtimeByIdAsync(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICinemaService/AddShowtime", ReplyAction="http://tempuri.org/ICinemaService/AddShowtimeResponse")]
        void AddShowtime(CinemaClient.CinemaServiceReference.ShowtimeDto showtimeDto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICinemaService/AddShowtime", ReplyAction="http://tempuri.org/ICinemaService/AddShowtimeResponse")]
        System.Threading.Tasks.Task AddShowtimeAsync(CinemaClient.CinemaServiceReference.ShowtimeDto showtimeDto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICinemaService/UpdateShowtime", ReplyAction="http://tempuri.org/ICinemaService/UpdateShowtimeResponse")]
        void UpdateShowtime(CinemaClient.CinemaServiceReference.ShowtimeDto showtimeDto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICinemaService/UpdateShowtime", ReplyAction="http://tempuri.org/ICinemaService/UpdateShowtimeResponse")]
        System.Threading.Tasks.Task UpdateShowtimeAsync(CinemaClient.CinemaServiceReference.ShowtimeDto showtimeDto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICinemaService/DeleteShowtime", ReplyAction="http://tempuri.org/ICinemaService/DeleteShowtimeResponse")]
        void DeleteShowtime(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICinemaService/DeleteShowtime", ReplyAction="http://tempuri.org/ICinemaService/DeleteShowtimeResponse")]
        System.Threading.Tasks.Task DeleteShowtimeAsync(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICinemaService/GetAllMovies", ReplyAction="http://tempuri.org/ICinemaService/GetAllMoviesResponse")]
        CinemaClient.CinemaServiceReference.MovieDto[] GetAllMovies();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICinemaService/GetAllMovies", ReplyAction="http://tempuri.org/ICinemaService/GetAllMoviesResponse")]
        System.Threading.Tasks.Task<CinemaClient.CinemaServiceReference.MovieDto[]> GetAllMoviesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICinemaService/GetAllHalls", ReplyAction="http://tempuri.org/ICinemaService/GetAllHallsResponse")]
        CinemaClient.CinemaServiceReference.HallDto[] GetAllHalls();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICinemaService/GetAllHalls", ReplyAction="http://tempuri.org/ICinemaService/GetAllHallsResponse")]
        System.Threading.Tasks.Task<CinemaClient.CinemaServiceReference.HallDto[]> GetAllHallsAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICinemaServiceChannel : CinemaClient.CinemaServiceReference.ICinemaService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CinemaServiceClient : System.ServiceModel.ClientBase<CinemaClient.CinemaServiceReference.ICinemaService>, CinemaClient.CinemaServiceReference.ICinemaService {
        
        public CinemaServiceClient() {
        }
        
        public CinemaServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CinemaServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CinemaServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CinemaServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public CinemaClient.CinemaServiceReference.ShowtimeDto[] GetAllShowtimes() {
            return base.Channel.GetAllShowtimes();
        }
        
        public System.Threading.Tasks.Task<CinemaClient.CinemaServiceReference.ShowtimeDto[]> GetAllShowtimesAsync() {
            return base.Channel.GetAllShowtimesAsync();
        }
        
        public CinemaClient.CinemaServiceReference.ShowtimeDto GetShowtimeById(string id) {
            return base.Channel.GetShowtimeById(id);
        }
        
        public System.Threading.Tasks.Task<CinemaClient.CinemaServiceReference.ShowtimeDto> GetShowtimeByIdAsync(string id) {
            return base.Channel.GetShowtimeByIdAsync(id);
        }
        
        public void AddShowtime(CinemaClient.CinemaServiceReference.ShowtimeDto showtimeDto) {
            base.Channel.AddShowtime(showtimeDto);
        }
        
        public System.Threading.Tasks.Task AddShowtimeAsync(CinemaClient.CinemaServiceReference.ShowtimeDto showtimeDto) {
            return base.Channel.AddShowtimeAsync(showtimeDto);
        }
        
        public void UpdateShowtime(CinemaClient.CinemaServiceReference.ShowtimeDto showtimeDto) {
            base.Channel.UpdateShowtime(showtimeDto);
        }
        
        public System.Threading.Tasks.Task UpdateShowtimeAsync(CinemaClient.CinemaServiceReference.ShowtimeDto showtimeDto) {
            return base.Channel.UpdateShowtimeAsync(showtimeDto);
        }
        
        public void DeleteShowtime(string id) {
            base.Channel.DeleteShowtime(id);
        }
        
        public System.Threading.Tasks.Task DeleteShowtimeAsync(string id) {
            return base.Channel.DeleteShowtimeAsync(id);
        }
        
        public CinemaClient.CinemaServiceReference.MovieDto[] GetAllMovies() {
            return base.Channel.GetAllMovies();
        }
        
        public System.Threading.Tasks.Task<CinemaClient.CinemaServiceReference.MovieDto[]> GetAllMoviesAsync() {
            return base.Channel.GetAllMoviesAsync();
        }
        
        public CinemaClient.CinemaServiceReference.HallDto[] GetAllHalls() {
            return base.Channel.GetAllHalls();
        }
        
        public System.Threading.Tasks.Task<CinemaClient.CinemaServiceReference.HallDto[]> GetAllHallsAsync() {
            return base.Channel.GetAllHallsAsync();
        }
    }
}
